[package]
name = "lsystem2"
version = "0.1.0"
edition = "2021"

# Дополнительные ключи и их определения см. на https://doc.rust-lang.org/cargo/reference/manifest.html.
[lib]
name = "lsystem2"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.20.2"
